language: node_js  

node_js: stable  

cache:
    apt: true
    directories:
        - node_modules 
before_install:
    - export TZ='Asia/Beijin'

install:
  - npm install  
  - npm install -g gulp
script:
  - hexo clean  
  - hexo g && gulp

after_script:
  - hexo d
branches:
  only:
    - src

