language: node_js  

node_js: stable  

cache:
    apt: true
    directories:
        - node_modules 
before_install:
    - export TZ='Asia/Beijin'

install:
  - npm install  
  - npm install -g gulp
script:
  - hexo clean  
  - hexo g && gulp

after_script:
  - hexo d
  - cd ./public
  - git init
  - git config user.name "chenjiujiu"
  - git config user.email "cjiujiu@icloud.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${ci}@${GH_REF}" master:master

  - git push --force --quiet "https://chenjiujiu:${coding}@${CO_REF}" master:master

  - git push --force --quiet "https://chenjiujiu:${gitee}@${GE_REF}" master:master

branches:
  only:
    - src
env:
 global:
   - GH_REF: github.com/chenjiujiu/chenjiujiu.github.io.git
   - CO_REF: git.coding.net/chenjiujiu/chenjiujiu.coding.io.git
   - GE_REF: gitee.com/chenjiujiu/chenjiujiu.gitee.io.git

